import type { Metadata } from 'next';
import 'swiper/css';

import fonts from '@/fonts';

import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fonts.classNames + ' bg-nature-500 text-text-500'}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
