export const adminQueryKeys = {
  ORDERS: 'admin-orders',
  ORDER_DETAILS: 'admin-order-details',
  USERS: 'admin-users',
  USER_DETAILS: 'admin-user-details',
  COMMENTS: 'admin-comments',
  EDIT_COMMENT_STATUS: 'admin-edit-comment-status',
  EDIT_ORDER_STATUS: 'admin-edit-order-status',
  UPLOAD_FACTOR: 'admin-upload-factor',
  CATEGORIES: 'admin-categories',
  ADD_CATEGORY: 'admin-add-category',
  EDIT_CATEGORY: 'admin-edit-category',
  DELETE_CATEGORY: 'admin-delete-category',
  PRODUCTS: 'admin-products',
  ADD_PRODUCT: 'admin-add-product',
  EDIT_PRODUCT: 'admin-edit-product',
  DELETE_PRODUCT: 'admin-delete-product',
  BRANDS: 'admin-brands',
  PETS: 'admin-pets',
  ADD_PET: 'admin-add-pet',
  EDIT_PET: 'admin-edit-pet',
  DELETE_PET: 'admin-delete-pet',
  DASHBOARD: 'admin-dashboard',
  SUB_CATEGORIES: 'admin-sub-categories',
  ADD_SUB_CATEGORY: 'admin-add-sub-category',
  EDIT_SUB_CATEGORY: 'admin-edit-sub-category',
  DELETE_SUB_CATEGORIES: 'admin-delete-sub-categories',
};
