export const adminQueryKeys = {
  ORDERS: 'admin-orders',
  ORDER_DETAILS: 'admin-order-details',
  USERS: 'admin-users',
  USER_DETAILS: 'admin-user-details',
  COMMENTS: 'admin-comments',
  EDIT_COMMENT_STATUS: 'admin-edit-comment-status',
  EDIT_ORDER_STATUS: 'admin-edit-order-status',
  UPLOAD_FACTOR: 'admin-upload-factor',
  CATEGORIES: 'admin-categories',
  ADD_CATEGORY: 'admin-add-category',
  EDIT_CATEGORY: 'admin-edit-category',
  DELETE_CATEGORY: 'admin-delete-category',
  PRODUCTS: 'admin-products',
  BRANDS: 'admin-brands',
  PETS: 'admin-pets',
};
